default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twitterkadai_development

production:
  <<: *default
  database: twitterkadai_production
  username: twitterkadai
  password: <%= ENV['TWITTERKADAI_DATABASE_PASSWORD'] %>
